### ISSUE TITLE
ModuleNotFoundError: No module named 'pennylane.ops.op_math'

### ISSUE THREAD

**Issue by leofang** [conda-forge/pennylane-lightning-gpu-feedstock#1]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
>>> import pennylane_lightning_gpu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leof/miniforge3/envs/my_pny_env/lib/python3.10/site-packages/pennylane_lightning_gpu/__init__.py", line 17, in <module>
    from .lightning_gpu import LightningGPU
  File "/home/leof/miniforge3/envs/my_pny_env/lib/python3.10/site-packages/pennylane_lightning_gpu/lightning_gpu.py", line 40, in <module>
    from pennylane.ops.op_math import Adjoint
ModuleNotFoundError: No module named 'pennylane.ops.op_math'
```

### Installed packages

```shell
# packages in environment at /home/leof/miniforge3/envs/my_pny_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
autograd                  1.5                pyhd8ed1ab_0    conda-forge
autoray                   0.6.3              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
cryptography              40.0.1                   pypi_0    pypi
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cupy                      12.0.0                   pypi_0    pypi
cuquantum-benchmarks      0.2.0                    pypi_0    pypi
cuquantum-python          22.11.0.1       py310hbe3ad0c_0    conda-forge
cuquantum-python-cu11     22.11.0                  pypi_0    pypi
custatevec                1.2.0                h0800d71_2    conda-forge
cutensor                  1.7.0.1              h12f7317_0    conda-forge
cutensornet               2.0.0           nompi_h0800d71_103    conda-forge
fastrlock                 0.8                      pypi_0    pypi
future                    0.18.3             pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
kokkos                    3.7.01               hf52228f_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
liblapacke                3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  3.0                pyhd8ed1ab_0    conda-forge
ninja                     1.11.1               h924138e_0    conda-forge
numpy                     1.24.2                   pypi_0    pypi
openssl                   3.1.0                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pennylane                 0.23.0             pyhd8ed1ab_0    conda-forge
pennylane-lightning       0.24.0                   pypi_0    pypi
pennylane-lightning-gpu   0.29.0                   pypi_0    pypi
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
psutil                    5.9.4                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.10         he550d4f_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
retworkx                  0.11.0                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
semantic_version          2.6.0                      py_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

### Environment info

```shell
active environment : my_pny_env
    active env location : /home/leof/miniforge3/envs/my_pny_env
            shell level : 4
       user config file : /home/leof/.condarc
 populated config files : /home/leof/miniforge3/.condarc
                          /home/leof/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.6.final.0
       virtual packages : __cuda=12.1=0
                          __linux=5.8.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/leof/miniforge3  (writable)
      conda av data dir : /home/leof/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/leof/miniforge3/pkgs
                          /home/leof/.conda/pkgs
       envs directories : /home/leof/miniforge3/envs
                          /home/leof/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.6 Linux/5.8.0-53-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1019:1019
             netrc file : None
           offline mode : False
```

**Comment by leofang** [comment]
It appears that my local env is corrupted (despite I created a new conda env for testing) and I got an outdated (0.23.0) Pennylane. Fixed with a fresh env enforced "pennylane>=0.29.0"

**Comment by leofang** [comment]
@vincentmr I noticed that this command
```
conda create -n my_pny_env python=3.10 pennylane-lightning-gpu
```
would pick up the old (before refactoring) `pennylane` (0.23) & `pennylane-lightning` (0.24) packages, as opposed to the new ones `pennylane-core` & `pennylane-lightning-core` (0.29), unless I use mamba (changing `conda` to `mamba`). Are you able to reproduce this observation?

**Comment by vincentmr** [comment]
Same here. Since PLL-GPU has a requirement `pennylane>=0.28`, we could put it in the recipe to be sure.

**Comment by leofang** [comment]
Thanks, Vincent, I think I found the issue, see the other ping 🙂

Yes, let's ping it here, but we also need to fix `pennylane-lightning-core`.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
It seems we still need to patch the repodata...😞 https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/425

**Comment by leofang** [comment]
btw manually constraining the solver would work:
```
conda install -c conda-forge "pennylane>=0.29" pennylane-lightning-gpu
```
or
```
conda create -n my_pny_env -c conda-forge python "pennylane>=0.29" pennylane-lightning-gpu
```

**Comment by leofang** [comment]
@vincentmr It appears that this now works because 0.29.1 was out (#4)
```
conda create -n my_pny_env python=3.10 pennylane-lightning-gpu
```
Was this a happy coincidence, or did you actually push for a patch release just to address this issue? 🙂

**Comment by vincentmr** [comment]
Nope, can't take credit. Maybe it's what you did, maybe some files got a refresh from merging `0.29.1`.
